import json
from dataclasses import dataclass
from pathlib import Path

from vexrag.exceptions import VexragError
from vexrag.rag import answer_with_context


@dataclass
class Case:
    """
    A single self-contained evaluation case.

    Contains everything needed for evaluation.

    Attributes:
        question: Question submitted to RAG.
        passages: Context passages used by RAG or supplied for evaluation.
        poison_target: Attacker's intended outcome or target behavior.
        expected_answer: Expected (gold) answer.
        answer: Answer generated by RAG.
    """

    question: str
    passages: list[str]
    poison_target: str
    expected_answer: str
    answer: str


class CasesLoadError(VexragError):
    """Raised when cases could not be loaded from a file."""


def load_cases_from_json(path: Path):
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, FileNotFoundError) as exc:
        raise CasesLoadError(f"Failed to load cases from {path}") from exc


async def run_scenario(scenario, llm_client) -> Case:
    answer = await answer_with_context(
        question=scenario["question"],
        passages=scenario["passages"],
        llm_client=llm_client,
    )
    return Case(**scenario, answer=answer["response"])
