name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - name: install uv and python
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: create venv and sync dependencies
        run: uv sync
      
      - name: install pytest
        run: uv pip install pytest
      
      - name: run tests
        run: uv run pytest .

